<#--

Copyright (C) 2011 Markus Junginger, greenrobot (http://greenrobot.de)     
                                                                           
This file is part of greenDAO Generator.                                   
                                                                           
greenDAO Generator is free software: you can redistribute it and/or modify 
it under the terms of the GNU General Public License as published by       
the Free Software Foundation, either version 3 of the License, or          
(at your option) any later version.                                        
greenDAO Generator is distributed in the hope that it will be useful,      
but WITHOUT ANY WARRANTY; without even the implied warranty of             
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              
GNU General Public License for more details.                               
                                                                           
You should have received a copy of the GNU General Public License          
along with greenDAO Generator.  If not, see <http://www.gnu.org/licenses/>.

-->
package ${schema.defaultJavaPackageDao}

import java.util.Map

import org.greenrobot.greendao.AbstractDao
import org.greenrobot.greendao.AbstractDaoSession
import org.greenrobot.greendao.database.Database
import org.greenrobot.greendao.identityscope.IdentityScopeType
import org.greenrobot.greendao.internal.DaoConfig

<#list schema.entities as entity>
import ${entity.javaPackage}.${entity.className}
</#list>

<#list schema.entities as entity>
import ${entity.javaPackageDao}.${entity.classNameDao}
</#list>

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
class ${schema.prefix}DaoSession (db:Database?, type:IdentityScopeType?, daoConfigMap: Map<Class<out AbstractDao<*, *>?>?, DaoConfig?> ) : AbstractDaoSession(db) {

<#list schema.entities as entity>
    private var ${entity.classNameDao?uncap_first}Config: DaoConfig = map.get(${entity.classNameDao}::class.java) as DaoConfig
    var ${entity.classNameDao?uncap_first}: ${entity.classNameDao}
</#list>        

    init {

<#list schema.entities as entity>
        ${entity.classNameDao?uncap_first}Config.initIdentityScope(type)
        ${entity.classNameDao?uncap_first} = ${entity.classNameDao}(${entity.classNameDao?uncap_first}Config, this)
        registerDao(${entity.className}::class.java, ${entity.classNameDao?uncap_first})
</#list>
    }
    
    fun clear() {
<#list schema.entities as entity>
        ${entity.classNameDao?uncap_first}Config.clearIdentityScope()
</#list>    
    }
}
